language: node_js
sudo: false
dist: precise
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
  - node_modules
node_js:
    - "8"
    - "6"
    - "4"
script:
  - npm test
after_success:
  - npm run coverall
